version: '3.8'
services:
  server:
    container_name: server
    image: tutungduong/bookshop-website:bookshop-server
    restart: on-failure
    depends_on:
      database:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/bookshop
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
    ports:
      - 8085:8085
    networks:
      - network

  database:
    container_name: database
    image: tutungduong/bookshop-website:database 
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bookshop
      LANG: C.UTF-8
    ports:
      - 3308:3306
    networks:
      - network
    volumes:
      - storage:/var/lib/mysql
    command: --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION" --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --general-log=1 --general-log-file=/tmp/mysql-general-log.log
    healthcheck:
      # Reference: https://stackoverflow.com/a/74905088
      test: 'cat /tmp/mysql-general-log.log | grep "Tcp port: 3306"'
      interval: 5s
      timeout: 30s
      retries: 20

volumes:
  storage:
    driver: local

networks:
  network:
    driver: bridge
